### ISSUE TITLE
create virtual Folders/Directories

### ISSUE THREAD

**Issue by madhums** [nodejitsu/node-cloudfiles#14]
How can I create Pseudo-Hierarchical Folders/Directories as specified [here](http://docs.rackspace.com/files/api/v1/cf-devguide/content/Pseudo-Hierarchical_Folders_Directories-d1e1580.html). 

I tried this by using addFile method, but it din't work as addFIle requires a local file or stream.

```
var options = { remote: 'images/test', headers: { 'Content-Type' : 'application/directory' } }
client.addFile(config.rs_container, options, callback);
```

**Comment by indexzero** [comment]
From the Rackspace README:

> To take advantage of this feature, the directory marker objects must also be created to represent the appropriate 
> directories. The following additional objects need to be created. A good convention would be to create these as zero- or 
> one-byte files with a Content-Type of application/directory.

So just make a simple one-byte file which you read from disk:

``` js
  fs.writeFileSync('/placeholder.txt', '-');

  //
  // Setup cloudfiles...
  //
  client.addFile('some-container', {
    remote: 'images/test',
    local: 'placeholder.txt',
    headers: {
      'Content-Type': 'application/directory'
    }
  }, function () { 
    //
    // Do stuff when it's done. 
    //
  });
```

We could define an API for this in the library, but it wouldn't be much more than just sugar for this.

**Comment by madhums** [comment]
ah! I think I missed using that zero-byte file. You're right an API for this would be more than sugar... Thank you!
