### ISSUE TITLE
addFile needs content-length?

### ISSUE THREAD

**Issue by anthonywebb** [nodejitsu/node-cloudfiles#22]
I'm trying to get a simple file to updload but am seeing an issue:

{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Cannot upload file without `content-length` header' }

Here is the simple code to post the file:

```
cloud.setAuth(function () {
    cloud.addFile('avatars', { remote: photoname, local: './uploads/temp.jpg' }, function (err, uploaded) {
        if(err){
            console.log(err);
        }
        else {
            console.log(uploaded);
        }
    });
});
```

Likely something small but I cant see to make it work?

Node is v 4.12

**Comment by pksunkara** [comment]
It already calculates content-length header from the given file

https://github.com/nodejitsu/node-cloudfiles/blob/v0.3.1/lib/cloudfiles/core.js#L351-353

**Comment by anthonywebb** [comment]
Thats what I thought, but for ome reason it isnt giving me it.  I know the file is there. hmm.

**Comment by anthonywebb** [comment]
Ah, looking and the file is corrupt, sorry, this was my bad.

**Comment by kainosnoema** [comment]
I had this same issue, but with a ReadableStream—obviously you can't always know the length of a stream ahead of time. Will this always be a requirement?
