### ISSUE TITLE
Is it possible to send a stream to .addfile without knowing content-length?

### ISSUE THREAD

**Issue by MeanwhileMedia** [nodejitsu/node-cloudfiles#26]
I am wondering if there is, or could ever be, a way to stream data to .addfile without sending options.headers['content-length'].  For example, if the file being sent to cloudfiles is not fully written (yet) when .addfile is called.

thanks

**Comment by bmeck** [comment]
Currently it is not supported, but support could be added by implementing : http://docs.rackspace.com/files/api/v1/cf-devguide/content/Chunked_Transfer_Encoding-d1e2092.html

**Comment by MeanwhileMedia** [comment]
Hello Bradley,

Thanks for the link.  That would be so sweet in this module.  I will definitely be following this repo to see if/when it gets implemented.

**Comment by bmeck** [comment]
Fixed : 130196b2e1f936171833149a800081ef888ce9a1

**Comment by MeanwhileMedia** [comment]
Oh my goodness! You already did it.  You sir, are a wizard.
