### ISSUE TITLE
Content type not getting sent correctly for .webm files

### ISSUE THREAD

**Issue by MeanwhileMedia** [nodejitsu/node-cloudfiles#27]
I apologize for my repeat issue posts, but I have been having a lot of trouble with this module.  Whether I set the content-type manually, or let the mime module do it for me, webm files still get stored as 'application/octet-stream' and will will therefore download, instead of play in browser (tested on firefox, and chrome).

My code (in case I'm missing something simple):

``` javascript
var upOpts = {
   headers: {
      'content-type': 'video/webm',
   },
   remote: newFilename, 
   local: path
};

cloudClient.addFile(Container.name, upOpts, function (err, uploaded) {
   if (err) { console.log('Error uploading '+path+': ' + err); }                            
}); 
```

**Comment by MeanwhileMedia** [comment]
Actually, I am guessing that content-type is never sent correctly. The content-type header is correct for some files (such as mp4) but I assume this is because rackspace is able to auto-set those.

**Comment by MeanwhileMedia** [comment]
I have determined that by updating the mimetypes.js file in the request module, the .webm file is sent correctly.  However, it still seems kind of strange to me that the request module is overwriting the header sent from this cloudfiles module.

I have marked this as an issue in the request github page.

**Comment by bmeck** [comment]
Reference : https://github.com/mikeal/request/issues/138
