### ISSUE TITLE
upload binary image data from memory

### ISSUE THREAD

**Issue by madhums** [nodejitsu/node-cloudfiles#32]
Is there any way I can use the binary image data present in the memory and upload it to cloudfiles. Here is my code

``` js
var form = new formidable.IncomingForm()
form.parse(req, function(err, fields, files) {
  im.resize({
    srcData: fs.readFileSync(files.images.path, 'binary'),
    width:   256
  }, function(err, stdout, stderr){
    if (err) throw err

    var options = {
        remote: files.images.name
      , headers: {
          'content-type': files.images.type
        }
      , stream: stdout } // stdout is binary data - stream or local option would throw an error
      , cdnUri = container.cdnUri

    client.addFile(config.rs_container, options, onUploadToContainer)

    function onUploadToContainer(err, uploaded) {
      if (err) throw err
      if (uploaded) res.write(cdnUri+files.images.name)
    }
  })
})

```

The `stdout` argument in the `im.resize` callback is binary data. `local` or `stream` option provided for `client.addFile` won't work obviously - hence an error is thrown.

I am trying not to save it as a file and then upload it to rackspace, instead I want to just use the binary data, upload to rackspace. Please correct me if I am wrong anywhere. Here is the [complete code](https://gist.github.com/1934446)

**Comment by sansculotte** [comment]
by 'binary' do you mean stdout in your example is a Buffer?

i'm asking, because i want to upload a 'file', which i have assembled in a Buffer, directly from memory. so i tried this module:
https://github.com/dodo/node-bufferstream

in this way:

``` javascript
var stream = new BufferStream({size: 'flexible'});
stream.write( new Buffer("test") );
var opts = { remote: 'test.txt', stream: stream };

cloudfiles.setAuth( function() {
   cloudfiles.addFile('test', opts, function(err, uploaded) { });
});
```

which just silently does nothing at all (where as when you pass a Buffer it'd complain about the missing pipe method)

i don't have time atm to dig deeper into what happens in the internals, so thanx for any input on this.

**Comment by madhums** [comment]
Yeah I meant `stdout` in my example. Ok, let me try it out and see...

**Comment by ajostergaard** [comment]
@madhums - did you manage to try it with bufferstream? Did it work?

**Comment by madhums** [comment]
yeah! it worked, i have implemented it in [node-imager](http://github.com/madhums/node-imager) . `stdout` itself was a buffer stream. (I used gm instead of imagemagick)
