### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by juansilva** [nodejitsu/node-cloudfiles#4]
Hello, 
Just installed this package with "npm install cloudfiles"
But when tried to use it throws an error "Error: Cannot find module 'eyes'"
Fixed it with "npm install eyes"
I take a look at your package.json and it's not listed under dependencies, shouldn't it be there??

Best Regards
Juan Silva

**Comment by Marak** [comment]
Eyes probably shouldn't be required, but npm install eyes will fix it.

I'll take a look at see why there is a eyes inspect statement in the code.

**Comment by indexzero** [comment]
Fixed in 0.2.2. 9cff784e810e6a7796f5a7bf81abc2b1dc2f1b1a
