### ISSUE TITLE
Can't Add Files

### ISSUE THREAD

**Issue by euforic** [nodejitsu/node-cloudfiles#6]
Using the following function 

``` javascript
 client.addFile('myContainer', 'newfile.txt', '/Users/christian/Desktop/test.txt', function (err, uploaded) {
    console.log(err);
  });
```

Getting the following when trying to add files

``` javascript
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Command failed: \ncurl: (3) <url> malformed\n',
  killed: false,
  code: 3,
  signal: null }
```

**Comment by Marak** [comment]
Hey! Could you please confirm your current version of node by typing `node -v` on your terminal? 

Also, could you try running the test suite and reporting the results so we have a better idea of what's going on?

Thanks!

**Comment by euforic** [comment]
Version 0.4.7 on OSX 10.6.7

**Comment by Marak** [comment]
Are you able to run the test suite? 

```
 vows test/*-test.js --spec
```

**Comment by indexzero** [comment]
Call client.setAuth() before calling client.addFile. This is a latent issue around CDN vs. non-CDN urls. Your code should be:

``` js
  client.setAuth(function () {
    client.addFile('myContainer', 'newfile.txt', '/Users/christian/Desktop/test.txt', function (err, uploaded) {
      console.log(err);
    });
  });
```

Let me know if that doesn't fix it.

**Comment by euforic** [comment]
Yes, works great thanks a lot guys!!!
